# -*- coding: utf-8 -*-
"""fact_check.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuRsxKJ7NWjeUOsV2pxQ-idZe-0A2UUZ
"""

# install package
#!pip install -qU langchain-naver

import getpass
import os
import json
import uuid
import requests
import re
from typing import Dict, Any
from typing import List, Optional
from langchain_naver import ChatClovaX
from dotenv import load_dotenv

load_dotenv()


api_key = os.getenv("CLOVASTUDIO_API_KEY")

if not os.getenv("CLOVASTUDIO_API_KEY"):
    os.environ["CLOVASTUDIO_API_KEY"] = getpass.getpass(
        "Enter your CLOVA Studio API Key: "
    )

os.environ["DART_API_KEY"] = os.getenv("DART_API_KEY")
os.environ["KRX_API_KEY"] = os.getenv("KRX_API_KEY")
os.environ["PUBLIC_DATA_API_KEY"] = os.getenv("PUBLIC_DATA_API_KEY")

def get_text_from_response(response):
    if hasattr(response, "content"):
        return response.content
    return str(response)


def safe_json_parse(response, original_claims=None):
    """
    JSON 파싱 실패해도 중간에 멈추지 않고 fallback 결과 반환
    """

    text = get_text_from_response(response)

    # 코드블록 제거
    text = re.sub(r"```json", "", text)
    text = re.sub(r"```", "", text)
    text = text.strip()

    # JSON 객체만 추출 시도
    json_match = re.search(r"\{.*\}", text, re.DOTALL)
    if json_match:
        json_text = json_match.group(0)
    else:
        json_text = text

    # 1차: 정상 JSON 파싱
    try:
        return json.loads(json_text)

    except json.JSONDecodeError as e:
        # print("[WARN] JSON Parsing Failed")
        # print("에러 위치:", e)
        # print("\n[LLM 원본 출력]")
        # print(text)
        print("\n" + "=" * 70)

    # 2차: trailing comma 제거 후 재시도
    fixed_text = re.sub(r",\s*}", "}", json_text)
    fixed_text = re.sub(r",\s*]", "]", fixed_text)

    try:
        return json.loads(fixed_text)

    except json.JSONDecodeError:
        # print("[WARN] JSON 복구 실패 → fallback 결과 생성")
        print("\n" + "=" * 70)

    # 3차: fallback 결과 반환
    fallback_claims = []

    if original_claims:
        for claim in original_claims:
            fallback_claims.append({
                "claim": claim,
                "company_name": "unknown",
                "stock_name": "unknown",
                "stock_code": "unknown",
                "market": "unknown",
                "date": "unknown",
                "period": "unknown",
                "api_target": "unknown",
                "metric": "unknown",
                "operator": "unknown",
                "value": "unknown",
                "unit": "unknown",
                "direction": "unknown",
                "verification_source": "unknown",
                "parse_status": "fallback"
            })

    return {
        "api_query_ready": False,
        "parse_success": False,
        "error_message": "LLM output could not be parsed as valid JSON",
        "claims": fallback_claims,
        "raw_output": text
    }

# =========================
# HCX 공통 호출 함수
# =========================
def call_hcx(prompt: str, original_claims: List[str] = None, debug: bool = False) -> Dict[str, Any]:

    messages=[
        {"role": "system", "content": "너는 주식 뉴스 팩트체크 라우터다. 반드시 JSON으로만 답변한다."},
        {"role": "user", "content": prompt}
    ]

    chat = ChatClovaX(
        model="HCX-007",
        temperature=0,
        top_p=0.1,
        max_tokens=None,
        timeout=None,
        max_retries=2,
    )

    try:
        response = chat.invoke(messages)
    except Exception as e:
        print(f"[ERROR] HCX API 호출 실패: {str(e)}")
        if debug:
            print(f"프롬프트: {prompt[:200]}...")
        return {
            "api_query_ready": False,
            "parse_success": False,
            "error_message": f"HCX API 호출 실패: {str(e)}",
            "claims": [],
            "raw_output": str(e)
        }

    result = safe_json_parse(
        response=response,
        original_claims=original_claims
    )

    if not result:
        print("[ERROR] HCX 응답에서 content를 찾지 못했습니다")
        raise ValueError(f"HCX 응답에서 content를 찾지 못했습니다: {response}")

    return result


# =========================
# 공통 라우터 프롬프트
# =========================
def build_router_prompt(claim: str) -> str:
    return f"""
너는 주식뉴스 팩트체크 공통 라우터다.

아래 Claim을 분석해서 어떤 공공 API가 가장 적합한지 판단해라.

선택 기준:
- DART: 기업 공시, 사업보고서, 분기보고서, 재무제표, 영업이익, 매출, 배당, 유상증자, 합병, 최대주주, 임원, 공급계약
- KRX: 코스피, 코스닥, 개별 종목 시세, 지수, 종가, 등락률, 거래량, 시가총액, 시장 통계
- PUBLIC_DATA: 물가, 금리, 환율, 고용, 수출입, GDP, 인구, 부동산, 정부 통계
- NONE: 공공 API로 검증하기 어렵거나 단순 의견/전망/해석

날짜 추출 규칙:
- Claim 안에 명확한 날짜가 있으면 그 날짜를 사용한다.
- 절대 임의로 날짜를 추측하지 않는다.

조건:
- markdown 금지
- ```json 금지
- key는 반드시 double quote 사용
- trailing comma 금지
- 값이 없으면 "unknown" 사용

Claim:
{claim}

반드시 JSON으로만 답변해라.

{{
  "date": "yyyy.mm.dd 또는 NONE",
  "domain": "stock/disclosure/economy/general",
  "api_target": "DART/KRX/PUBLIC_DATA/NONE",
  "claim_type": "company_disclosure/financial_statement/index_price/stock_price/trading_volume/macro_statistic/etc",
  "claim": {claim},
  "need_fact_check": "Y 또는 N",
  "reason": "해당 API를 선택한 이유",
  "next_prompt": "DART_PROMPT/KRX_PROMPT/PUBLIC_DATA_PROMPT/NONE"
}}
"""


# =========================
# DART 전용 프롬프트
# =========================
def build_dart_prompt(claim: str) -> str:
    return f"""
너는 OPEN DART API 전용 팩트체크 라우터다.

아래 Claim을 OPEN DART API로 검증하기 위해 필요한 조회 정보를 추출해라.

OPEN DART로 적합한 Claim:
- 공시 여부
- 사업보고서, 반기보고서, 분기보고서
- 매출, 영업이익, 당기순이익 등 재무제표 수치
- 배당, 유상증자, 무상증자, 감자
- 합병, 분할, 영업양수도
- 최대주주 변경
- 임원 변경
- 단일판매·공급계약 체결

Claim:
{claim}

반드시 JSON으로만 답변해라.

{{
  "claim": "{claim}",
  "api_target": "DART",
  "claim_type": "company_disclosure/financial_statement/dividend/capital_increase/merger/shareholder/executive/contract/etc",
  "entities": {{
    "company_name": null,
    "stock_code": null,
    "corp_code": null,
    "report_type": null,
    "date": null,
    "start_date": null,
    "end_date": null,
    "keywords": []
  }},
  "dart_api_candidates": [
    {{
      "api_name": "공시검색 API",
      "endpoint": "/api/list.json",
      "purpose": "공시 제출 여부 및 보고서 조회"
    }}
  ],
  "api_params": {{
    "corp_code": null,
    "bgn_de": null,
    "end_de": null,
    "pblntf_ty": null,
    "last_reprt_at": "Y"
  }},
  "query_plan": [
    "조회해야 할 DART 데이터"
  ],
  "reason": "DART로 검증해야 하는 이유"
}}
"""


# =========================
# KRX 전용 프롬프트
# =========================
def build_krx_prompt(claim: str) -> str:
    return f"""
너는 KRX Open API 전용 팩트체크 라우터다.

아래 Claim을 KRX Open API로 검증하기 위해 필요한 조회 정보를 추출해라.

KRX로 적합한 Claim:
- 코스피/코스닥 지수
- 종가, 시가, 고가, 저가
- 전일 대비 등락률
- 연초 대비 등락률
- 거래량, 거래대금
- 개별 종목 시세
- 시장 전체 통계

날짜 추출 규칙:
- Claim에 명확한 날짜(예: "12일", "2024.10.15", "10월 15일")가 있으면 추출해라.
- 없으면 null로 둔다.

Claim:
{claim}

반드시 JSON으로만 답변해라.

{{
  "claim": "{claim}",
  "api_target": "KRX",
  "claim_type": "index_price/stock_price/trading_volume/market_cap/change_rate/etc",
  "entities": {{
    "market": "KOSPI 또는 KOSDAQ 또는 ALL",
    "index_name": "코스피 지수 또는 코스닥 지수 또는 특정 종목명",
    "company_name": null,
    "stock_code": null,
    "date": "yyyy-mm-dd 형식 또는 null",
    "base_date": "비교 기준 날짜 (전일 등)",
    "compare_date": null,
    "metrics": ["지수값", "등락률", "거래량" 등 추출된 지표들]
  }},
  "krx_api_candidates": [
    {{
      "api_name": "KOSPI 시리즈 일별시세정보",
      "purpose": "코스피 지수 시세 검증"
    }},
    {{
      "api_name": "KOSDAQ 시리즈 일별시세정보",
      "purpose": "코스닥 지수 시세 검증"
    }}
  ],
  "api_params": {{
    "basDd": "yyyymmdd 형식의 날짜",
    "market": "KOSPI 또는 KOSDAQ",
    "isuCd": null
  }},
  "query_plan": [
    "조회해야 할 KRX 데이터"
  ],
  "reason": "KRX로 검증해야 하는 이유"
}}
"""


# =========================
# 공공데이터포털 전용 프롬프트
# =========================
def build_public_data_prompt(claim: str) -> str:
    return f"""
너는 공공데이터포털 전용 팩트체크 라우터다.

아래 Claim을 공공데이터포털 또는 정부 통계 API로 검증하기 위해 필요한 조회 정보를 추출해라.

공공데이터포털로 적합한 Claim:
- 물가, 소비자물가지수
- 금리, 환율
- 고용률, 실업률
- 수출입 통계
- GDP, 경제성장률
- 인구, 가구, 지역 통계
- 부동산 가격, 거래량
- 정부·공공기관 통계

Claim:
{claim}

반드시 JSON으로만 답변해라.

{{
  "claim": "{claim}",
  "api_target": "PUBLIC_DATA",
  "claim_type": "macro_statistic/price_index/employment/export_import/interest_rate/exchange_rate/real_estate/population/etc",
  "entities": {{
    "statistic_name": null,
    "institution": null,
    "region": null,
    "period": null,
    "start_date": null,
    "end_date": null,
    "unit": null,
    "keywords": []
  }},
  "public_api_candidates": [
    {{
      "api_name": "사용할 공공데이터포털 API 이름",
      "institution": "제공기관",
      "purpose": "해당 API 사용 목적"
    }}
  ],
  "api_params": {{
    "serviceKey": null,
    "pageNo": 1,
    "numOfRows": 10,
    "startDate": null,
    "endDate": null,
    "region": null
  }},
  "query_plan": [
    "조회해야 할 공공데이터"
  ],
  "reason": "공공데이터포털로 검증해야 하는 이유"
}}
"""

# =========================
# 결과 전용 프롬프트
# =========================
def build_reason_prompt(claim: str, fact_check: dict) -> str:
    return f"""
너는 주식 뉴스 팩트체크 결과 설명 생성기다.

아래 Claim과 계산 결과를 바탕으로 최종 reason을 작성해라.

주의사항:
- fact_check_result 값은 절대 바꾸지 마라.
- 주어진 계산 결과만 근거로 설명해라.
- 없는 수치나 근거를 만들지 마라.
- 설명은 한국어로 작성해라.
- JSON으로만 답변해라.

Claim:
{claim}

Fact Check Result:
{json.dumps(fact_check, ensure_ascii=False, indent=2)}

반드시 아래 JSON 형식으로만 답변해라.

{{
  "fact_check_result": "{fact_check.get("fact_check_result")}",
  "reason": "판정 이유를 2~4문장으로 설명",
  "summary": "한 문장 요약",
  "evidence_summary": [
    "핵심 근거 1",
    "핵심 근거 2"
  ],
  "caution": "주의할 점 또는 한계",
  "link": "관련 링크"
}}
"""

# -------------------------
# DART API 호출
# -------------------------
DART_API_KEY = os.getenv("DART_API_KEY")


def call_dart_api(detail_result: Dict[str, Any]) -> Dict[str, Any]:

    api_params = detail_result.get("api_params", {})

    url = "https://opendart.fss.or.kr/api/list.json"

    params = {
        "crtfc_key": DART_API_KEY,
        "corp_code": api_params.get("corp_code"),
        "bgn_de": api_params.get("bgn_de"),
        "end_de": api_params.get("end_de"),
        "pblntf_ty": api_params.get("pblntf_ty"),
        "last_reprt_at": api_params.get("last_reprt_at", "Y")
    }

    # None 제거
    params = {k: v for k, v in params.items() if v is not None}

    response = requests.get(url, params=params)
    response.raise_for_status()

    return response.json()


# -------------------------
# KRX API 호출
# -------------------------
KRX_API_KEY = os.getenv("KRX_API_KEY")


def call_krx_single(api_path: str, bas_dd: str) -> Dict[str, Any]:
    url = f"https://openapi.krx.co.kr/svc/apis/idx/{api_path}"

    headers = {
        "AUTH_KEY": KRX_API_KEY
    }

    params = {
        "basDd": bas_dd
    }

    response = requests.get(url, headers=headers, params=params)
    response.raise_for_status()

    return response.json()


def get_first_row(response_json: Dict[str, Any]) -> Dict[str, Any]:
    rows = response_json.get("OutBlock_1", [])
    if not rows:
        return {}
    return rows[0]


def call_krx_api(detail_result: Dict[str, Any]) -> Dict[str, Any]:
    entities = detail_result.get("entities", {})
    api_params = detail_result.get("api_params", {})

    market = entities.get("market") or "KOSPI"
    current_date = entities.get("date") or api_params.get("basDd")
    base_date = entities.get("base_date") or entities.get("compare_date")

    # 날짜 형식 변환
    current_date = parse_date_to_yyyymmdd(current_date)
    base_date = parse_date_to_yyyymmdd(base_date)

    if not current_date:
        from datetime import datetime
        current_date = datetime.now().strftime("%Y%m%d")

    if not base_date:
        from datetime import datetime, timedelta
        yesterday = datetime.now() - timedelta(days=1)
        base_date = yesterday.strftime("%Y%m%d")

    result = {
        "current": {},
        "base": {}
    }

    market_api_map = {
        "KOSPI": "kospi_dd_trd",
        "KOSDAQ": "kosdaq_dd_trd"
    }

    markets = ["KOSPI", "KOSDAQ"] if market == "ALL" else [market]

    for m in markets:
        api_path = market_api_map.get(m)

        if not api_path:
            continue

        try:
            current_response = call_krx_single(api_path, current_date)
            base_response = call_krx_single(api_path, base_date)

            result["current"][m] = get_first_row(current_response)
            result["base"][m] = get_first_row(base_response)
        except Exception as e:
            print(f"[ERROR] KRX API 호출 실패 ({m}, {current_date}): {str(e)}")
            result["current"][m] = {}
            result["base"][m] = {}

    return result


# -------------------------
# 공공데이터포털 API 호출
# -------------------------
PUBLIC_DATA_API_KEY = os.getenv("PUBLIC_DATA_API_KEY")


def call_public_data_api(detail_result: Dict[str, Any]) -> Dict[str, Any]:

    entities = detail_result.get("entities", {})

    statistic_name = entities.get("statistic_name")

    # 예시:
    # 소비자물가지수 API
    if statistic_name == "소비자물가지수":

        url = "https://api.odcloud.kr/api/example"

        params = {
            "serviceKey": PUBLIC_DATA_API_KEY,
            "page": 1,
            "perPage": 10
        }

    # 예시:
    # 환율 API
    elif statistic_name == "환율":

        url = "https://api.odcloud.kr/api/example2"

        params = {
            "serviceKey": PUBLIC_DATA_API_KEY
        }

    else:
        return {
            "message": "현재 지원되지 않는 공공데이터 API 유형입니다."
        }

    response = requests.get(url, params=params)
    response.raise_for_status()

    return response.json()


# =========================
# API 라우팅 실행
# =========================
def execute_api(detail_result: Dict[str, Any]) -> Dict[str, Any]:

    api_target = detail_result.get("api_target")

    try:

        # -----------------
        # DART
        # -----------------
        if api_target == "DART":

            api_response = call_dart_api(detail_result)

        # -----------------
        # KRX
        # -----------------
        elif api_target == "KRX":

            api_response = call_krx_api(detail_result)

        # -----------------
        # PUBLIC DATA
        # -----------------
        elif api_target == "PUBLIC_DATA":

            api_response = call_public_data_api(detail_result)

        else:
            api_response = {
                "message": "호출 가능한 API가 없습니다."
            }

        return {
            "success": True,
            "api_target": api_target,
            "api_response": api_response
        }

    except Exception as e:

        return {
            "success": False,
            "api_target": api_target,
            "error": str(e)
        }


def run_factcheck_pipeline(claim: str):

    # ---------------------
    # 1차: Router
    # ---------------------
    router_prompt = build_router_prompt(claim)

    router_result = call_hcx(router_prompt, original_claims=[claim])

    next_prompt = router_result.get("next_prompt")

    # ---------------------
    # 2차: 전용 Prompt
    # ---------------------
    if next_prompt == "DART_PROMPT":

        detail_prompt = build_dart_prompt(claim)
        print(detail_prompt)

    elif next_prompt == "KRX_PROMPT":

        detail_prompt = build_krx_prompt(claim)
        print(detail_prompt)

    elif next_prompt == "PUBLIC_DATA_PROMPT":

        detail_prompt = build_public_data_prompt(claim)
        print(detail_prompt)

    else:

        return {
            "router_result": router_result,
            "detail_result": None,
            "api_result": None
        }

    detail_result = call_hcx(detail_prompt, original_claims=[claim])

    # ---------------------
    # 3차: 실제 API 호출
    # ---------------------
    api_result = execute_api(detail_result)

    return {
        "router_result": router_result,
        "detail_result": detail_result,
        "api_result": api_result
    }

# =========================
# Claim에서 숫자 추출
# =========================
def extract_numbers_from_claim(claim: str) -> List[float]:
    """
    Claim 문장에서 숫자 추출
    예: '각각 9.9%, 21.7% 하락' -> [9.9, 21.7]
    """
    numbers = re.findall(r"[-+]?\d+(?:\.\d+)?", claim)
    return [float(n) for n in numbers]


# =========================
# 문자열 숫자 변환
# =========================
def to_float(value) -> Optional[float]:
    """
    '85,000', '-9.9%', '21.7' 같은 값을 float로 변환
    """
    if value is None:
        return None

    value = str(value)
    value = value.replace(",", "")
    value = value.replace("%", "")
    value = value.strip()

    try:
        return float(value)
    except ValueError:
        return None


def parse_date_to_yyyymmdd(date_str: Optional[str]) -> Optional[str]:
    """
    다양한 날짜 형식을 yyyymmdd로 변환
    예: "2023-10-12" -> "20231012"
         "2023.10.12" -> "20231012"
         "12일" (현재 기준으로 추정) -> 적절한 날짜
    """
    if not date_str:
        return None

    import re
    from datetime import datetime, timedelta

    date_str = str(date_str).strip()

    # 이미 yyyymmdd 형식
    if re.match(r'^\d{8}$', date_str):
        return date_str

    # yyyy-mm-dd 형식
    match = re.match(r'(\d{4})-(\d{2})-(\d{2})', date_str)
    if match:
        return f"{match.group(1)}{match.group(2)}{match.group(3)}"

    # yyyy.mm.dd 형식
    match = re.match(r'(\d{4})\.(\d{2})\.(\d{2})', date_str)
    if match:
        return f"{match.group(1)}{match.group(2)}{match.group(3)}"

    # "12일" 같은 형식 (현재 기준으로 추정)
    match = re.match(r'(\d{1,2})일', date_str)
    if match:
        today = datetime.now()
        day = int(match.group(1))
        target_date = today.replace(day=day)
        if target_date > today:
            target_date = target_date.replace(month=target_date.month - 1 if target_date.month > 1 else 12)
        return target_date.strftime("%Y%m%d")

    return None


# =========================
# KRX 응답에서 수치 추출
# =========================
def extract_krx_answer(detail_result: Dict[str, Any], api_response: Dict[str, Any]) -> Dict[str, Any]:
    entities = detail_result.get("entities", {})
    metrics = entities.get("metrics", [])
    market = entities.get("market")

    rows = api_response.get("OutBlock_1", [])

    if not rows:
        return {
            "success": False,
            "reason": "KRX 응답 데이터가 없습니다."
        }

    row = rows[0]

    extracted = {
        "market": market,
        "values": {}
    }

    # KRX 응답 컬럼명은 API별로 다를 수 있으므로 후보 컬럼 사용
    column_candidates = {
        "종가": ["CLSPRC_IDX", "clsprcIdx", "종가"],
        "등락률": ["FLUC_RT", "fltRt", "등락률"],
        "거래량": ["ACC_TRDVOL", "accTrdvol", "거래량"],
        "거래대금": ["ACC_TRDVAL", "accTrdval", "거래대금"],
        "시가총액": ["MKTCAP", "mktcap", "시가총액"]
    }

    for metric_name, columns in column_candidates.items():
        for col in columns:
            if col in row:
                extracted["values"][metric_name] = to_float(row.get(col))
                break

    return {
        "success": True,
        "source": "KRX",
        "extracted": extracted,
        "raw_row": row
    }


# =========================
# DART 응답에서 수치 추출
# =========================
def extract_dart_answer(detail_result: Dict[str, Any], api_response: Dict[str, Any]) -> Dict[str, Any]:
    """
    DART 공시검색 API는 보통 공시 목록을 반환합니다.
    실제 재무 수치 검증은 단일회사 주요계정 API 응답에 더 적합합니다.

    여기서는 두 경우를 모두 처리합니다.
    """

    # 공시검색 API: list
    if "list" in api_response:
        disclosures = api_response.get("list", [])

        return {
            "success": True,
            "source": "DART",
            "type": "disclosure_list",
            "disclosure_count": len(disclosures),
            "extracted": {
                "has_disclosure": len(disclosures) > 0,
                "first_report_name": disclosures[0].get("report_nm") if disclosures else None,
                "first_receipt_date": disclosures[0].get("rcept_dt") if disclosures else None
            },
            "raw_rows": disclosures[:5]
        }

    # 재무제표 API: list 안에 account_nm, thstrm_amount 등이 있는 경우
    rows = api_response.get("list", [])

    keywords = detail_result.get("entities", {}).get("keywords", [])

    extracted_values = []

    for row in rows:
        account_name = row.get("account_nm", "")

        for keyword in keywords:
            if keyword in account_name:
                extracted_values.append({
                    "account_name": account_name,
                    "current_amount": to_float(row.get("thstrm_amount")),
                    "previous_amount": to_float(row.get("frmtrm_amount")),
                    "raw": row
                })

    return {
        "success": True,
        "source": "DART",
        "type": "financial_statement",
        "extracted": extracted_values,
        "raw_rows": rows[:5]
    }


# =========================
# 공공데이터 응답에서 수치 추출
# =========================
def extract_public_data_answer(detail_result: Dict[str, Any], api_response: Dict[str, Any]) -> Dict[str, Any]:
    """
    공공데이터포털 API는 응답 구조가 API마다 다르므로
    item/items/data/list 후보를 순서대로 탐색합니다.
    """

    rows = []

    if "data" in api_response:
        rows = api_response.get("data", [])

    elif "items" in api_response:
        items = api_response.get("items", {})
        if isinstance(items, dict):
            rows = items.get("item", [])
        elif isinstance(items, list):
            rows = items

    elif "response" in api_response:
        body = api_response.get("response", {}).get("body", {})
        items = body.get("items", {})
        if isinstance(items, dict):
            rows = items.get("item", [])
        elif isinstance(items, list):
            rows = items

    if isinstance(rows, dict):
        rows = [rows]

    extracted_values = []

    for row in rows[:10]:
        for key, value in row.items():
            num = to_float(value)
            if num is not None:
                extracted_values.append({
                    "field": key,
                    "value": num,
                    "raw": row
                })

    return {
        "success": True,
        "source": "PUBLIC_DATA",
        "extracted": extracted_values[:10],
        "raw_rows": rows[:5]
    }


# =========================
# API별 정답 수치 추출
# =========================
def extract_answer_from_api(
    detail_result: Dict[str, Any],
    api_result: Dict[str, Any]
) -> Dict[str, Any]:

    if not api_result.get("success"):
        return {
            "success": False,
            "reason": "API 호출 실패",
            "error": api_result.get("error")
        }

    api_target = api_result.get("api_target")
    api_response = api_result.get("api_response", {})

    if api_target == "KRX":
        return extract_krx_answer(detail_result, api_response)

    elif api_target == "DART":
        return extract_dart_answer(detail_result, api_response)

    elif api_target == "PUBLIC_DATA":
        return extract_public_data_answer(detail_result, api_response)

    else:
        return {
            "success": False,
            "reason": "지원하지 않는 API 대상입니다."
        }


# =========================
# Claim 숫자와 API 수치 비교
# =========================
def compare_claim_with_answer(
    claim: str,
    answer_result: Dict[str, Any],
    tolerance: float = 0.2
) -> Dict[str, Any]:
    """
    tolerance:
    - 퍼센트포인트 기준 허용 오차
    - 예: Claim 9.9%, API 10.0%면 차이 0.1 → TRUE
    """

    claim_numbers = extract_numbers_from_claim(claim)

    if not answer_result.get("success"):
        return {
            "fact_check_result": "UNKNOWN",
            "reason": answer_result.get("reason", "정답 수치 추출 실패"),
            "claim_numbers": claim_numbers,
            "api_numbers": []
        }

    api_numbers = []

    extracted = answer_result.get("extracted")

    if isinstance(extracted, dict):
        values = extracted.get("values", {})
        for v in values.values():
            if isinstance(v, (int, float)):
                api_numbers.append(v)

        if "has_disclosure" in extracted:
            return {
                "fact_check_result": "SUPPORTED" if extracted["has_disclosure"] else "NOT_SUPPORTED",
                "reason": "DART 공시 존재 여부를 기준으로 판단했습니다.",
                "claim_numbers": claim_numbers,
                "api_numbers": api_numbers,
                "evidence": extracted
            }

    elif isinstance(extracted, list):
        for item in extracted:
            for key in ["value", "current_amount", "previous_amount"]:
                if key in item and isinstance(item[key], (int, float)):
                    api_numbers.append(item[key])

    if not claim_numbers or not api_numbers:
        return {
            "fact_check_result": "UNKNOWN",
            "reason": "Claim 또는 API 응답에서 비교 가능한 숫자를 찾지 못했습니다.",
            "claim_numbers": claim_numbers,
            "api_numbers": api_numbers,
            "evidence": answer_result.get("extracted")
        }

    comparisons = []

    for claim_num in claim_numbers:
        closest_api_num = min(api_numbers, key=lambda x: abs(x - claim_num))
        diff = abs(claim_num - closest_api_num)

        comparisons.append({
            "claim_value": claim_num,
            "api_value": closest_api_num,
            "difference": diff,
            "matched": diff <= tolerance
        })

    matched_count = sum(1 for c in comparisons if c["matched"])

    if matched_count == len(comparisons):
        result = "TRUE"
        reason = "Claim의 모든 수치가 API 응답 수치와 허용 오차 내에서 일치합니다."

    elif matched_count > 0:
        result = "PARTLY_TRUE"
        reason = "Claim의 일부 수치만 API 응답 수치와 일치합니다."

    else:
        result = "FALSE"
        reason = "Claim의 수치가 API 응답 수치와 일치하지 않습니다."

    return {
        "fact_check_result": result,
        "reason": reason,
        "claim_numbers": claim_numbers,
        "api_numbers": api_numbers,
        "comparisons": comparisons,
        "evidence": answer_result.get("extracted")
    }


import re
from typing import Dict, Any, List, Optional


# =========================
# 증감 방향 추출
# =========================
def extract_direction(claim: str) -> str:
    if any(word in claim for word in ["상승", "증가", "올랐다", "늘었다", "개선"]):
        return "UP"
    if any(word in claim for word in ["하락", "감소", "내렸다", "줄었다", "악화"]):
        return "DOWN"
    return "UNKNOWN"


# =========================
# 비교 유형 추출
# =========================
def extract_compare_type(claim: str) -> str:
    if "전일 대비" in claim:
        return "DAY_OVER_DAY"
    if "연초" in claim or "연초 대비" in claim:
        return "YEAR_TO_DATE"
    if "전년 대비" in claim or "지난해보다" in claim:
        return "YEAR_OVER_YEAR"
    if "전분기 대비" in claim:
        return "QUARTER_OVER_QUARTER"
    if "배 증가" in claim or "배 늘" in claim:
        return "MULTIPLE"
    return "DIRECT"


# =========================
# Claim 수치 추출 (개선)
# =========================
def extract_claim_numbers(claim: str) -> List[Dict[str, Any]]:
    """
    숫자와 그 맥락을 함께 추출하여 더 정확한 비교 가능
    예: "179.09포인트(2.29%)" -> [{"value": 179.09, "context": "포인트", ...}, ...]
    """
    pattern = r'([-+]?\d+(?:\.\d+)?)\s*([가-힣%]*)(?:\(([^)]+)\))?'
    matches = re.finditer(pattern, claim)

    numbers_with_context = []
    for match in matches:
        try:
            value = float(match.group(1))
            context = match.group(2)
            paren_content = match.group(3)

            numbers_with_context.append({
                "value": value,
                "context": context,
                "paren_content": paren_content,
                "position": match.start()
            })
        except (ValueError, TypeError):
            pass

    return numbers_with_context


# =========================
# 증감률 계산
# =========================
def calculate_change_rate(base_value: float, current_value: float) -> Optional[float]:
    """
    증감률 = (현재값 - 기준값) / 기준값 * 100
    """
    if base_value is None or current_value is None:
        return None

    if base_value == 0:
        return None

    return round(((current_value - base_value) / base_value) * 100, 2)


# =========================
# 배수 계산
# =========================
def calculate_multiple(base_value: float, current_value: float) -> Optional[float]:
    """
    배수 = 현재값 / 기준값
    """
    if base_value is None or current_value is None:
        return None

    if base_value == 0:
        return None

    return round(current_value / base_value, 2)


# =========================
# KRX 현재값/기준값 추출
# =========================
def extract_krx_base_current_values(
    detail_result: Dict[str, Any],
    api_result: Dict[str, Any]
) -> Dict[str, Any]:
    """
    KRX의 경우 api_response를 아래 형태로 맞추는 것을 권장합니다.

    예:
    api_response = {
        "current": {
            "KOSPI": {...},
            "KOSDAQ": {...}
        },
        "base": {
            "KOSPI": {...},
            "KOSDAQ": {...}
        }
    }
    """

    api_response = api_result.get("api_response", {})

    current_data = api_response.get("current", {})
    base_data = api_response.get("base", {})

    markets = []

    entities = detail_result.get("entities", {})
    market = entities.get("market")

    if market == "ALL":
        markets = ["KOSPI", "KOSDAQ"]
    elif market:
        markets = [market]

    # market이 없으면 기본값으로 KOSPI 사용
    if not markets:
        markets = ["KOSPI"]

    results = []

    for m in markets:
        current_row = current_data.get(m, {})
        base_row = base_data.get(m, {})

        # 데이터가 없으면 건너뛰기
        if not current_row and not base_row:
            results.append({
                "target": m,
                "base_value": None,
                "current_value": None,
                "calculated_change_rate": None,
                "error": "API 응답에 해당 시장 데이터가 없습니다."
            })
            continue

        current_value = (
            to_float(current_row.get("CLSPRC_IDX"))
            or to_float(current_row.get("clsprcIdx"))
            or to_float(current_row.get("종가"))
        )

        base_value = (
            to_float(base_row.get("CLSPRC_IDX"))
            or to_float(base_row.get("clsprcIdx"))
            or to_float(base_row.get("종가"))
        )

        change_rate = calculate_change_rate(base_value, current_value)

        results.append({
            "target": m,
            "base_value": base_value,
            "current_value": current_value,
            "calculated_change_rate": change_rate,
            "raw_current": current_row,
            "raw_base": base_row
        })

    return {
        "source": "KRX",
        "values": results
    }


# =========================
# DART 현재값/기준값 추출
# =========================
def extract_dart_base_current_values(
    detail_result: Dict[str, Any],
    api_result: Dict[str, Any]
) -> Dict[str, Any]:
    """
    DART 재무제표 API 응답에서 현재기/전기 금액을 추출합니다.
    주요 컬럼:
    - account_nm
    - thstrm_amount: 당기
    - frmtrm_amount: 전기
    """

    api_response = api_result.get("api_response", {})
    rows = api_response.get("list", [])

    keywords = detail_result.get("entities", {}).get("keywords", [])

    results = []

    for row in rows:
        account_name = row.get("account_nm", "")

        matched = False
        for keyword in keywords:
            if keyword in account_name:
                matched = True
                break

        if not matched:
            continue

        current_value = to_float(row.get("thstrm_amount"))
        base_value = to_float(row.get("frmtrm_amount"))

        change_rate = calculate_change_rate(base_value, current_value)
        multiple = calculate_multiple(base_value, current_value)

        results.append({
            "target": account_name,
            "base_value": base_value,
            "current_value": current_value,
            "calculated_change_rate": change_rate,
            "calculated_multiple": multiple,
            "raw": row
        })

    return {
        "source": "DART",
        "values": results
    }


# =========================
# 공공데이터 현재값/기준값 추출
# =========================
def extract_public_base_current_values(
    detail_result: Dict[str, Any],
    api_result: Dict[str, Any]
) -> Dict[str, Any]:
    """
    공공데이터는 API마다 구조가 다르므로,
    실제 프로젝트에서는 통계별 adapter를 따로 두는 것이 좋습니다.

    여기서는 예시로 api_response가 아래 형태라고 가정합니다.

    api_response = {
        "base": {"value": 100.0},
        "current": {"value": 103.0}
    }
    """

    api_response = api_result.get("api_response", {})

    base_value = to_float(api_response.get("base", {}).get("value"))
    current_value = to_float(api_response.get("current", {}).get("value"))

    change_rate = calculate_change_rate(base_value, current_value)
    multiple = calculate_multiple(base_value, current_value)

    return {
        "source": "PUBLIC_DATA",
        "values": [
            {
                "target": detail_result.get("entities", {}).get("statistic_name"),
                "base_value": base_value,
                "current_value": current_value,
                "calculated_change_rate": change_rate,
                "calculated_multiple": multiple
            }
        ]
    }


# =========================
# API별 기준값/현재값 추출 통합
# =========================
def extract_base_current_values(
    claim: str,
    detail_result: Dict[str, Any],
    api_result: Dict[str, Any]
) -> Dict[str, Any]:

    api_target = detail_result.get("api_target")
    claim_type = detail_result.get("claim_type")

    api_response = api_result.get("api_response", {})

    if api_target == "DART":
        # 공시검색 API 결과
        if "list" in api_response and claim_type != "financial_statement":
            return calculate_dart_disclosure_search(
                claim=claim,
                detail_result=detail_result,
                api_response=api_response
            )

        # 재무제표 계산
        return extract_dart_base_current_values(
            detail_result=detail_result,
            api_result=api_result
        )

    if api_target == "KRX":
        return extract_krx_base_current_values(detail_result, api_result)

    if api_target == "PUBLIC_DATA":
        return extract_public_base_current_values(detail_result, api_result)

    return {
        "source": api_target,
        "values": []
    }


# =========================
# Claim 수치와 계산값 비교
# =========================
def compare_calculated_values_with_claim(
    claim: str,
    calculated_result: Dict[str, Any],
    tolerance: float = 0.3
) -> Dict[str, Any]:

    claim_numbers = extract_claim_numbers(claim)
    compare_type = extract_compare_type(claim)
    direction = extract_direction(claim)

    values = calculated_result.get("values", [])

    if not claim_numbers:
        return {
            "fact_check_result": "UNKNOWN",
            "reason": "Claim에서 비교할 수치를 찾지 못했습니다.",
            "claim_numbers": [],
            "calculated_values": values
        }

    comparisons = []

    # 숫자들을 비율 변화 기준으로 정렬 (백분율이 포함된 것들)
    percentage_numbers = [
        n for n in claim_numbers
        if n.get("paren_content") and "%" in str(n.get("paren_content"))
    ]
    other_numbers = [n for n in claim_numbers if n not in percentage_numbers]

    # 계산값이 있는 항목들과 비교
    for idx, calculated_item in enumerate(values):
        if idx >= len(percentage_numbers):
            break

        claim_item = percentage_numbers[idx]
        claim_value = claim_item.get("value")

        if compare_type == "MULTIPLE":
            calculated_value = calculated_item.get("calculated_multiple")
            metric = "multiple"
        else:
            calculated_value = calculated_item.get("calculated_change_rate")
            metric = "change_rate"

        if calculated_value is None:
            comparisons.append({
                "target": calculated_item.get("target"),
                "claim_item": claim_item,
                "claim_value": claim_value,
                "calculated_value": None,
                "matched": False,
                "reason": "계산값이 없습니다."
            })
            continue

        # 방향 정규화
        if direction == "DOWN" and metric == "change_rate":
            normalized_claim_value = -abs(claim_value)
        elif direction == "UP" and metric == "change_rate":
            normalized_claim_value = abs(claim_value)
        else:
            normalized_claim_value = claim_value

        diff = abs(normalized_claim_value - calculated_value)

        comparisons.append({
            "target": calculated_item.get("target"),
            "metric": metric,
            "base_value": calculated_item.get("base_value"),
            "current_value": calculated_item.get("current_value"),
            "claim_item": claim_item,
            "claim_value": normalized_claim_value,
            "calculated_value": calculated_value,
            "difference": round(diff, 4),
            "matched": diff <= tolerance
        })

    # 모든 숫자 저장
    all_claim_values = [n.get("value") for n in claim_numbers]

    if not comparisons:
        return {
            "fact_check_result": "UNKNOWN",
            "reason": "API 응답에서 추출할 데이터가 부족하거나 Claim 수치와 비교할 계산값이 없습니다.",
            "claim_numbers": all_claim_values,
            "all_extracted_numbers": claim_numbers,
            "calculated_values": values,
            "debug": {
                "claim_count": len(claim_numbers),
                "values_count": len(values),
                "percentage_numbers": len(percentage_numbers)
            }
        }

    matched_count = sum(1 for c in comparisons if c["matched"])

    if matched_count == len(comparisons):
        result = "TRUE"
        reason = "기준값과 현재값으로 계산한 결과가 Claim 수치와 일치합니다."

    elif matched_count > 0:
        result = "PARTLY_TRUE"
        reason = "일부 항목만 Claim 수치와 일치합니다."

    else:
        result = "FALSE"
        reason = "계산한 증감률 또는 배수가 Claim 수치와 일치하지 않습니다."

    return {
        "fact_check_result": result,
        "reason": reason,
        "compare_type": compare_type,
        "direction": direction,
        "claim_numbers": all_claim_values,
        "all_extracted_numbers": claim_numbers,
        "comparisons": comparisons
    }


# =========================
# 1. DART 공시검색 응답 정규화
# =========================
def normalize_dart_disclosure_list(api_response: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    DART 공시검색 API 응답에서 list만 안전하게 추출
    """

    status = api_response.get("status")
    message = api_response.get("message")

    if status != "000":
        return []

    disclosures = api_response.get("list", [])

    if not isinstance(disclosures, list):
        return []

    return disclosures


# =========================
# 2. Claim 키워드 추출
# =========================
def extract_disclosure_keywords_from_claim(claim: str) -> List[str]:
    """
    Claim에서 공시 검색용 핵심 키워드 추출
    """

    keyword_map = {
        "자사주": ["자기주식", "자사주"],
        "자기주식": ["자기주식"],
        "배당": ["배당", "현금ㆍ현물배당"],
        "유상증자": ["유상증자"],
        "무상증자": ["무상증자"],
        "감자": ["감자"],
        "합병": ["합병"],
        "분할": ["분할"],
        "최대주주": ["최대주주"],
        "대표이사": ["대표이사"],
        "임원": ["임원"],
        "공급계약": ["단일판매", "공급계약", "계약체결"],
        "수주": ["단일판매", "공급계약", "계약체결"],
        "전환사채": ["전환사채"],
        "신주인수권부사채": ["신주인수권부사채"],
        "주주총회": ["주주총회"],
        "실적": ["영업실적", "잠정실적", "매출액", "영업이익"],
        "영업이익": ["영업이익", "영업실적", "잠정실적"],
        "매출": ["매출액", "영업실적", "잠정실적"],
    }

    keywords = []

    for word, mapped_keywords in keyword_map.items():
        if word in claim:
            keywords.extend(mapped_keywords)

    # 중복 제거
    return list(dict.fromkeys(keywords))


# =========================
# 3. 공시명 매칭 점수 계산
# =========================
def calculate_report_match_score(
    report_name: str,
    keywords: List[str]
) -> Dict[str, Any]:

    matched_keywords = []

    for keyword in keywords:
        if keyword in report_name:
            matched_keywords.append(keyword)

    score = 0.0

    if keywords:
        score = round(len(matched_keywords) / len(keywords), 4)
        # print(score)

    return {
        "report_name": report_name,
        "matched_keywords": matched_keywords,
        "score": score
    }


# =========================
# 4. 날짜 범위 매칭
# =========================
def is_date_in_range(
    rcept_dt: Optional[str],
    start_date: Optional[str],
    end_date: Optional[str]
) -> bool:
    """
    rcept_dt, start_date, end_date는 YYYYMMDD 문자열 기준
    """

    if not rcept_dt:
        return False

    if start_date and rcept_dt < start_date:
        return False

    if end_date and rcept_dt > end_date:
        return False

    return True


# =========================
# 5. DART 공시검색 계산
# =========================
def calculate_dart_disclosure_search(
    claim: str,
    detail_result: Dict[str, Any],
    api_response: Dict[str, Any],
    min_score: float = 0.3
) -> Dict[str, Any]:
    """
    DART 공시검색 결과를 바탕으로 Claim을 검증하기 위한 계산 코드

    판단 기준:
    1. 공시 목록 존재 여부
    2. 공시명(report_nm)이 Claim 키워드와 일치하는지
    3. 접수일자(rcept_dt)가 조회 기간에 포함되는지
    """

    disclosures = normalize_dart_disclosure_list(api_response)

    entities = detail_result.get("entities", {})
    api_params = detail_result.get("api_params", {})

    start_date = (
        entities.get("start_date")
        or api_params.get("bgn_de")
    )
    end_date = (
        entities.get("end_date")
        or api_params.get("end_de")
    )

    llm_keywords = entities.get("keywords", [])
    rule_keywords = extract_disclosure_keywords_from_claim(claim)

    keywords = list(dict.fromkeys(llm_keywords + rule_keywords))

    matched_disclosures = []

    for row in disclosures:
        report_name = row.get("report_nm", "")
        rcept_dt = row.get("rcept_dt")

        score_result = calculate_report_match_score(
            report_name=report_name,
            keywords=keywords
        )

        date_matched = is_date_in_range(
            rcept_dt=rcept_dt,
            start_date=start_date,
            end_date=end_date
        )

        matched = (
            score_result["score"] >= min_score
            and date_matched
        )

        matched_disclosures.append({
            "corp_name": row.get("corp_name"),
            "corp_code": row.get("corp_code"),
            "stock_code": row.get("stock_code"),
            "report_name": report_name,
            "receipt_no": row.get("rcept_no"),
            "receipt_date": rcept_dt,
            "matched_keywords": score_result["matched_keywords"],
            "keyword_score": score_result["score"],
            "date_matched": date_matched,
            "matched": matched
        })

    final_matches = [
        item for item in matched_disclosures
        if item["matched"]
    ]

    if final_matches:
        fact_check_result = "SUPPORTED"
        reason = "Claim과 관련된 DART 공시가 조회 기간 내에서 확인되었습니다."
    elif disclosures:
        fact_check_result = "NOT_ENOUGH_EVIDENCE"
        reason = "DART 공시는 조회되었지만 Claim 키워드 또는 기간 조건과 충분히 일치하지 않습니다."
    else:
        fact_check_result = "NOT_SUPPORTED"
        reason = "조회 조건에 해당하는 DART 공시가 확인되지 않았습니다."

    return {
        "source": "DART",
        "calculation_type": "disclosure_search",
        "fact_check_result": fact_check_result,
        "reason": reason,
        "total_disclosure_count": len(disclosures),
        "matched_count": len(final_matches),
        "keywords": keywords,
        "date_range": {
            "start_date": start_date,
            "end_date": end_date
        },
        "matched_disclosures": final_matches[:10],
        "all_disclosure_candidates": matched_disclosures[:20]
    }

# =========================
# 최종 팩트체크 파이프라인
# =========================
def run_full_factcheck_pipeline(claim: str) -> Dict[str, Any]:

    # 1. Router + 전용 Prompt + API 호출
    pipeline_result = run_factcheck_pipeline(claim)

    detail_result = pipeline_result.get("detail_result")
    api_result = pipeline_result.get("api_result")

    if detail_result is None or api_result is None:
        return {
            **pipeline_result,
            "answer_result": None,
            "fact_check": {
                "fact_check_result": "UNKNOWN",
                "reason": "API 호출 대상이 없습니다."
            }
        }

    # 2. API 응답에서 정답 수치 추출
    answer_result = extract_answer_from_api(
        detail_result=detail_result,
        api_result=api_result
    )

    # 3. Claim과 API 수치 비교
    fact_check = compare_claim_with_answer(
        claim=claim,
        answer_result=answer_result,
        tolerance=0.2
    )

    reason_result = generate_reason(
        claim=claim,
        fact_check=fact_check
    )

    # return {
    #     **pipeline_result,
    #     "answer_result": answer_result,
    #     "fact_check": fact_check,
    #     "reason_result": reason_result
    # }

    return {
        "fact_check": {
            **fact_check,
            "llm_reason": reason_result
        },
        "reason_result": reason_result
    }


# =========================
# 최종 파이프라인 교체
# =========================
def run_full_factcheck_pipeline_v2(claim: str) -> Dict[str, Any]:

    # 1. Router + 전용 Prompt + 실제 API 호출
    pipeline_result = run_factcheck_pipeline(claim)

    detail_result = pipeline_result.get("detail_result")
    api_result = pipeline_result.get("api_result")

    if not detail_result or not api_result:
        return {
            **pipeline_result,
            "calculated_result": None,
            "fact_check": {
                "fact_check_result": "UNKNOWN",
                "reason": "API 호출 결과가 없습니다."
            }
        }

    # 2. 기준값/현재값 추출
    calculated_result = extract_base_current_values(
        claim=claim,
        detail_result=detail_result,
        api_result=api_result
    )

    # 3. 증감률/배수 계산 후 Claim과 비교
    fact_check = compare_calculated_values_with_claim(
        claim=claim,
        calculated_result=calculated_result,
        tolerance=0.3
    )

    return {
        **pipeline_result,
        "calculated_result": calculated_result,
        "fact_check": fact_check
    }


def generate_reason(claim: str, fact_check: dict) -> dict:
    prompt = build_reason_prompt(claim, fact_check)
    return call_hcx(prompt, original_claims=[claim])


def run_full_factcheck_pipeline_v3(claim: str) -> Dict[str, Any]:

    pipeline_result = run_factcheck_pipeline(claim)

    detail_result = pipeline_result.get("detail_result")
    api_result = pipeline_result.get("api_result")

    if not detail_result or not api_result:
        return {
            **pipeline_result,
            "calculated_result": None,
            "fact_check": {
                "fact_check_result": "UNKNOWN",
                "reason": "API 호출 결과가 없습니다."
            }
        }

    calculated_result = extract_base_current_values(
        claim=claim,
        detail_result=detail_result,
        api_result=api_result
    )

    if calculated_result.get("calculation_type") == "disclosure_search":
        fact_check = {
            "fact_check_result": calculated_result.get("fact_check_result"),
            "reason": calculated_result.get("reason"),
            "matched_count": calculated_result.get("matched_count"),
            "matched_disclosures": calculated_result.get("matched_disclosures")
        }
    else:
        fact_check = compare_calculated_values_with_claim(
            claim=claim,
            calculated_result=calculated_result,
            tolerance=0.3
        )

    return {
        **pipeline_result,
        "calculated_result": calculated_result,
        "fact_check": fact_check
    }

import json


def print_factcheck_result(result: dict):
    claim = result.get("claim") or result.get("router_result", {}).get("claim")
    route = result.get("router_result", {})
    detail = result.get("detail_result", {})
    fact = result.get("fact_check", {})
    calc = result.get("calculated_result", {})

    print("\n" + "=" * 70)
    print("뉴스 Claim 팩트체크 결과")
    print("=" * 70)

    # print(f"\n[Claim]\n{claim}")

    # print("\n[라우팅 결과]")
    # print(f"- API 대상: {route.get('api_target')}")
    # print(f"- Claim 유형: {route.get('claim_type')}")
    # print(f"- 검증 필요 여부: {route.get('need_fact_check')}")
    # print(f"- 선택 이유: {route.get('reason')}")

    print("\n[상세 분석]")
    print(f"- API 대상: {detail.get('api_target')}")
    print(f"- 상세 유형: {detail.get('claim_type')}")

    entities = detail.get("entities", {})
    if entities:
        print("- 추출 엔티티:")
        for k, v in entities.items():
            print(f"  · {k}: {v}")

    print("\n[최종 판정]")
    print(f"- 결과: {fact.get('fact_check_result')}")
    print(f"- 이유: {fact.get('reason')}")

    comparisons = fact.get("comparisons", [])
    if comparisons:
        print("\n[수치 비교]")
        for idx, item in enumerate(comparisons, 1):
            print(f"\n  {idx}) {item.get('target')}")
            print(f"   - 기준값: {item.get('base_value')}")
            print(f"   - 현재값: {item.get('current_value')}")
            print(f"   - Claim 값: {item.get('claim_value')}")
            print(f"   - 계산값: {item.get('calculated_value')}")
            print(f"   - 차이: {item.get('difference')}")
            print(f"   - 일치 여부: {'일치' if item.get('matched') else '불일치'}")

    matched_disclosures = fact.get("matched_disclosures", [])
    if matched_disclosures:
        print("\n[매칭된 공시]")
        for idx, item in enumerate(matched_disclosures, 1):
            print(f"\n  {idx}) {item.get('report_name')}")
            print(f"   - 기업명: {item.get('corp_name')}")
            print(f"   - 종목코드: {item.get('stock_code')}")
            print(f"   - 접수일자: {item.get('receipt_date')}")
            print(f"   - 접수번호: {item.get('receipt_no')}")
            print(f"   - 매칭 키워드: {item.get('matched_keywords')}")
            print(f"   - 키워드 점수: {item.get('keyword_score')}")
            print(f"   - 날짜 일치: {item.get('date_matched')}")

    print("\n[계산 결과 요약]")
    print(json.dumps(calc, ensure_ascii=False, indent=2))

    print("\n" + "=" * 70)


# =========================
# 실행 예시
# =========================
if __name__ == "__main__":

    # claim = "SK하이닉스가 142억 원 규모의 자기주식 처분을 결정했고, 한화엔진은6l 3541억 원 규모의 선박용 엔진 공급계약을 체결하는 등 주요 상장사들의 대규모 공시가 잇따랐습니다."
    # claim = "12일 장중 한 때 ‘7999’을 찍으며 전고점을 새로 썼던 코스피가 하락 전환하며 약세 마감했다. 이날 코스피는 전일 대비 179.09포인트(2.29%) 내린 7643.15에 장을 마쳤다. 이날 지수는 전일보다 131.17포인트(1.68%) 오른 7953.41에 거래를 시작한 뒤 7999까지 치솟으며 8000피를 목전에 뒀었지만, 외국인과 기관의 매도 공세로 장중 하락 전환했다."
    claim = "22일 오전 10시51분 현재 코스피는 전일 대비 43.21포인트(0.55%) 오른 7858.80에 거래되고 있다."

    # result = run_full_factcheck_pipeline(claim)
    # result = run_full_factcheck_pipeline_v2(claim)
    result = run_full_factcheck_pipeline_v3(claim)

    # print("\n\n=== LLM 응답 ===\n")
    # print(json.dumps(result, ensure_ascii=False, indent=2))

    print_factcheck_result(result)
